language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r coupleboard *
  - mkdir -p deploy
  - mv coupleboard.zip deploy/coupleboard.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: iph-coupleboard
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: iph-coupleboard
    key: coupleboard.zip
    bundle_type: zip
    application: coupleboard
    deployment_group: coupleboard-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - cjd0030@gmail.com